### ISSUE TITLE
command string - TypeError: unicode strings are not supported, please encode to bytes

### ISSUE THREAD

**Issue by mungewell** [tbird20d/grabserial#22]
When attempting to send a serial command on startup I get the following errror.

```
smart@smart:~/grabserial-master$ python3 ./grabserial -T -b 115200 -d /dev/ttyUSB0 -c 'logcat -c;logcat -vtime'
Traceback (most recent call last):
  File "./grabserial", line 530, in <module>
    grab(sys.argv[1:])
  File "./grabserial", line 402, in grab
    sd.write(command + "\n")
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 532, in write
    d = to_bytes(data)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 63, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: {!r}'.format(seq))
TypeError: unicode strings are not supported, please encode to bytes: 'logcat -c;logcat -vtime\n'
```

Using Python3 on Xubuntu. Fails on xfce-term and xterm.

**Comment by tbird20d** [comment]
I just did a big sweep through grabserial to try to fix all unicode string issues
(especially with Python 3).  Can you try grabserial version 1.9.8, and let me know if you 
are still having problems.

Thanks,
 -- Tim
